### ISSUE TITLE
Chart category values should plot in ascending order

### ISSUE THREAD

**Issue by PromiseFru** [smswithoutborders/SMSWithoutBorders-Telemetry-FE#31]
For category months, values should start from January to December respectively. Month orders shouldn't be mixed up. e.g data contains months August, December, and February. Chart should plot data in the order February, August, December

**Comment by PromiseFru** [comment]
@Vanessa-Kris this doesn't work for chrome browser.

**Comment by Vanessa-Kris** [comment]
fixed.
